sudo: required
services:
   - docker
   
before_install:
   - docker build -t phan2410/hello-vertx .
   
script:
   - echo "skipping tests"
   
after_success:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push phan2410/hello-vertx

deploy:
   provider: elasticbeanstalk
   region:   "ap-south-1"
   app:      "hello-vertx"
   env:      "HelloVertx-env"
   bucket_name: "elasticbeanstalk-ap-south-1-988383364451"
   bucket_path: "hello-vertx"
   on:
      branch: main
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
